"""Hermetic tests for XLSX/HTML artifact parity and canonical freshness.

The tests exercise the *real* exporters and read the generated bytes back, so a
shared in-memory projection cannot mask a rendering/parsing mismatch.
"""

from __future__ import annotations

import json
from datetime import date
from pathlib import Path

import openpyxl

from tournament_scheduler.excel.plan_exporter import SeasonPlanExporter
from tournament_scheduler.html import CANCELLED_TOURNAMENTS_FILENAME
from tournament_scheduler.html.html_exporter import HtmlExporter
from tournament_scheduler.models import SeasonPlan, Team, Tournament
from tournament_scheduler.pipeline.export_parity import (
    STATUS_FAIL,
    STATUS_NOT_CHECKABLE,
    STATUS_PASS,
    verify_export_parity,
)
from tournament_scheduler.pipeline.export_parity.gate import publish_parity_gate
from tournament_scheduler.season_planner import SeasonPlanner
from tournament_scheduler.spond import SpondExporter

REVISION = "rev-abc123"
OTHER_REVISION = "rev-def456"


def _games(teams):
    return SeasonPlanner.generate_round_robin_games(teams, parallel_games=2)


def _fixture() -> SeasonPlan:
    teams_u10 = [Team(club=f"Club{i}", label=f"U10-{i}", age_group="U10") for i in range(4)]
    # Two legitimate same-day/same-host/same-age events (duplicate Holmen U12).
    dup_a = [Team(club="Holmen", label=f"Holmen A{i}", age_group="U12") for i in range(4)]
    dup_b = [Team(club="Holmen", label=f"Holmen B{i}", age_group="U12") for i in range(4)]
    tournaments = [
        Tournament(
            id="rvv-0001",
            date=date(2026, 10, 10),
            arena="Jar Isforum",
            age_group="U10",
            teams=teams_u10,
            games=_games(teams_u10),
            host_club="Jar",
            start_time="09:00",
        ),
        Tournament(
            id="rvv-0002",
            date=date(2026, 11, 7),
            arena="Holmen ishall",
            age_group="U12",
            teams=dup_a,
            games=_games(dup_a),
            host_club="Holmen",
            start_time="10:00",
        ),
        Tournament(
            id="rvv-0003",
            date=date(2026, 11, 7),
            arena="Holmen ishall",
            age_group="U12",
            teams=dup_b,
            games=_games(dup_b),
            host_club="Holmen",
            start_time="10:00",
        ),
        Tournament(
            id="rvv-0004",
            date=date(2026, 12, 5),
            arena="Jar Isforum",
            age_group="U10",
            teams=teams_u10,
            games=_games(teams_u10),
            host_club="Jar",
            start_time="09:00",
            cancelled=True,
            cancellation_reason="Regionalt sperret helg",
        ),
    ]
    # Reverse the XLSX row order relative to the HTML chronological order.
    return SeasonPlan(tournaments=list(reversed(tournaments)), start_date=date(2026, 10, 1), end_date=date(2027, 4, 30))


def _approval_status() -> dict:
    return {
        "tournaments": [
            {"tournament_id": "rvv-0001", "status": "approved", "placement_locked": True, "participants_locked": False},
            {"tournament_id": "rvv-0002", "status": "pending_review", "placement_locked": False, "participants_locked": False},
        ]
    }


def _booking_status() -> dict:
    return {
        "tournaments": [
            {"tournament_id": "rvv-0001", "status": "confirmed_booked", "needs_attention": False},
            {"tournament_id": "rvv-0002", "status": "confirmed_not_booked", "needs_attention": True},
        ]
    }


def _export_pair(tmp_path: Path, revision: str = REVISION) -> tuple[Path, Path, Path]:
    export_dir = tmp_path / "export"
    export_dir.mkdir()
    plan = _fixture()
    ice = {"U10": 150, "U12": 120}
    approval = _approval_status()
    booking = _booking_status()
    xlsx = export_dir / "season_plan.xlsx"
    html = export_dir / "season_plan.html"
    SeasonPlanExporter().export(
        plan,
        str(xlsx),
        ice_time_for_age_group=ice,
        decision_status={"approval": approval, "booking": booking},
        season_metadata={"season": "2026-2027", "canonical_revision": revision},
    )
    HtmlExporter().export(
        plan,
        str(html),
        pipeline_meta={
            "canonical_revision": revision,
            "approval_status": approval,
            "booking_status": booking,
        },
        ice_time_for_age_group=ice,
    )
    SpondExporter().export(
        plan,
        str(export_dir / "season_plan_spond.xlsx"),
        ice_time_for_age_group=ice,
        season_metadata={"season": "2026-2027", "canonical_revision": revision},
    )
    return export_dir, xlsx, html


def test_real_exports_are_artifact_parity_clean(tmp_path):
    export_dir, _, _ = _export_pair(tmp_path)

    report = verify_export_parity(export_dir)

    assert report["status"] == STATUS_PASS, report["reasons"]
    assert report["primary"]["tournament_count"] == 4
    assert report["secondary"]["tournament_count"] == 4
    assert report["canonical_revision"] == REVISION


def test_two_same_day_events_compare_by_stable_id_not_row_order(tmp_path):
    export_dir, _, _ = _export_pair(tmp_path)
    report = verify_export_parity(export_dir)
    assert report["status"] == STATUS_PASS
    # Both duplicate Holmen U12 events survive as distinct ids.
    assert not report["comparison"]["duplicate_ids"]["xlsx"]
    assert not report["comparison"]["duplicate_ids"]["html"]


def test_edited_excel_booking_cell_fails_with_id_and_field(tmp_path):
    export_dir, xlsx, _ = _export_pair(tmp_path)
    workbook = openpyxl.load_workbook(xlsx)
    sheet = workbook["Sesongoversikt"]
    header = [cell.value for cell in sheet[1]]
    status_col = header.index("Bookingsstatus") + 1
    id_col = header.index("Turnerings-ID") + 1
    target_row = next(
        row for row in range(2, sheet.max_row + 1) if sheet.cell(row=row, column=id_col).value == "rvv-0001"
    )
    sheet.cell(row=target_row, column=status_col).value = "confirmed_not_booked"
    workbook.save(xlsx)

    report = verify_export_parity(export_dir)

    assert report["status"] == STATUS_FAIL
    mismatches = report["comparison"]["mismatches"]
    assert any(m["tournament_id"] == "rvv-0001" and m["field"] == "booking_status" for m in mismatches)


def test_edited_html_booking_flag_fails(tmp_path):
    export_dir, _, html = _export_pair(tmp_path)
    text = html.read_text(encoding="utf-8")
    text = text.replace('"bs": "confirmed_not_booked"', '"bs": "confirmed_booked"', 1)
    html.write_text(text, encoding="utf-8")

    report = verify_export_parity(export_dir)

    assert report["status"] == STATUS_FAIL
    assert any(m["field"] == "booking_status" for m in report["comparison"]["mismatches"])


def test_one_sided_cancellation_fails(tmp_path):
    export_dir, xlsx, _ = _export_pair(tmp_path)
    workbook = openpyxl.load_workbook(xlsx)
    sheet = workbook["Sesongoversikt"]
    header = [cell.value for cell in sheet[1]]
    date_col = header.index("Dato") + 1
    id_col = header.index("Turnerings-ID") + 1
    reason_col = header.index("Avlysningsårsak") + 1
    cancelled_col = header.index("Avlyst") + 1
    target_row = next(
        row for row in range(2, sheet.max_row + 1) if sheet.cell(row=row, column=id_col).value == "rvv-0004"
    )
    sheet.cell(row=target_row, column=date_col).value = "05.12.2026"
    sheet.cell(row=target_row, column=reason_col).value = ""
    sheet.cell(row=target_row, column=cancelled_col).value = ""
    workbook.save(xlsx)

    report = verify_export_parity(export_dir)

    assert report["status"] == STATUS_FAIL
    assert any(m["tournament_id"] == "rvv-0004" and m["field"] == "cancelled" for m in report["comparison"]["mismatches"])


def test_missing_artifact_is_not_checkable(tmp_path):
    export_dir, _, html = _export_pair(tmp_path)
    html.unlink()

    report = verify_export_parity(export_dir)

    assert report["status"] == STATUS_NOT_CHECKABLE
    assert report["reasons"][0]["code"] == "artifact_missing"


def test_corrupt_xlsx_is_not_checkable(tmp_path):
    export_dir, xlsx, _ = _export_pair(tmp_path)
    xlsx.write_bytes(b"not a workbook")

    report = verify_export_parity(export_dir)

    assert report["status"] == STATUS_NOT_CHECKABLE
    assert report["reasons"][0]["code"] == "artifact_unreadable"


def test_stale_revision_fails_freshness_even_when_pair_matches(tmp_path):
    export_dir, _, _ = _export_pair(tmp_path, revision=REVISION)

    report = verify_export_parity(export_dir, required_canonical_revision=OTHER_REVISION)

    assert report["status"] == STATUS_FAIL
    assert any(reason["code"] == "stale_canonical_revision" for reason in report["reasons"])


def test_artifact_revision_mismatch_fails(tmp_path):
    export_dir, xlsx, _ = _export_pair(tmp_path, revision=REVISION)
    # Re-export only the workbook with a different embedded revision.
    workbook = openpyxl.load_workbook(xlsx)
    sheet = workbook["Eksportmetadata"]
    for row in sheet.iter_rows():
        if row[0].value == "Kanonisk revisjon":
            row[1].value = OTHER_REVISION
    workbook.save(xlsx)

    report = verify_export_parity(export_dir)

    assert report["status"] == STATUS_FAIL
    assert any(reason["code"] == "artifact_revision_mismatch" for reason in report["reasons"])


def test_publish_gate_passes_clean_pair_and_blocks_mismatch(tmp_path):
    export_dir, xlsx, _ = _export_pair(tmp_path)
    assert publish_parity_gate(export_dir=export_dir, repo_dir=tmp_path) is None

    workbook = openpyxl.load_workbook(xlsx)
    sheet = workbook["Sesongoversikt"]
    header = [cell.value for cell in sheet[1]]
    arena_col = header.index("Arena") + 1
    sheet.cell(row=2, column=arena_col).value = "Feil arena"
    workbook.save(xlsx)

    blocked = publish_parity_gate(export_dir=export_dir, repo_dir=tmp_path)
    assert blocked is not None
    assert blocked.status == "failed"
    assert any(
        evidence.startswith("export_parity_mismatch=") and "arena" in evidence
        for evidence in blocked.evidence
        if isinstance(evidence, str)
    )


def test_publish_gate_ignores_non_season_bundle(tmp_path):
    export_dir = tmp_path / "export"
    export_dir.mkdir()
    (export_dir / "season_plan.html").write_text("<h1>legacy</h1>", encoding="utf-8")
    assert publish_parity_gate(export_dir=export_dir, repo_dir=tmp_path) is None


def test_write_parity_report_persists_json(tmp_path):
    from tournament_scheduler.pipeline.export_parity import write_parity_report

    export_dir, _, _ = _export_pair(tmp_path)
    report = verify_export_parity(export_dir)
    path = write_parity_report(export_dir, report)

    assert json.loads(Path(path).read_text(encoding="utf-8"))["status"] == STATUS_PASS


def test_export_parity_command_exit_codes(tmp_path):
    import argparse

    from tournament_scheduler.cli.export_parity_command import _cmd_export_parity

    export_dir, xlsx, _ = _export_pair(tmp_path)
    namespace = argparse.Namespace(
        export_dir=str(export_dir),
        basename="season_plan",
        season=None,
        season_root=None,
        expected_revision=None,
        allow_historical=True,
        write_report=False,
        json=True,
    )
    assert _cmd_export_parity(namespace) == 0

    workbook = openpyxl.load_workbook(xlsx)
    workbook["Sesongoversikt"].cell(row=2, column=4).value = "Feil arena"
    workbook.save(xlsx)
    assert _cmd_export_parity(namespace) == 1


def test_deleted_excel_row_is_reported_missing(tmp_path):
    export_dir, xlsx, _ = _export_pair(tmp_path)
    workbook = openpyxl.load_workbook(xlsx)
    workbook["Sesongoversikt"].delete_rows(2)
    workbook.save(xlsx)

    report = verify_export_parity(export_dir)

    assert report["status"] == STATUS_FAIL
    assert report["comparison"]["extra_ids"]


def test_duplicated_excel_id_is_detected(tmp_path):
    export_dir, xlsx, _ = _export_pair(tmp_path)
    workbook = openpyxl.load_workbook(xlsx)
    sheet = workbook["Sesongoversikt"]
    header = [cell.value for cell in sheet[1]]
    id_col = header.index("Turnerings-ID") + 1
    sheet.cell(row=3, column=id_col).value = sheet.cell(row=2, column=id_col).value
    workbook.save(xlsx)

    report = verify_export_parity(export_dir)

    assert report["status"] == STATUS_FAIL
    assert report["comparison"]["duplicate_ids"]["xlsx"]


def test_participant_and_date_change_are_detected(tmp_path):
    export_dir, xlsx, _ = _export_pair(tmp_path)
    workbook = openpyxl.load_workbook(xlsx)
    sheet = workbook["Sesongoversikt"]
    header = [cell.value for cell in sheet[1]]
    teams_col = header.index("Lag") + 1
    date_col = header.index("Dato") + 1
    sheet.cell(row=2, column=teams_col).value = "Helt Feil Lag, U10-0"
    sheet.cell(row=2, column=date_col).value = "01.01.2027"
    workbook.save(xlsx)

    report = verify_export_parity(export_dir)

    assert report["status"] == STATUS_FAIL
    fields = {m["field"] for m in report["comparison"]["mismatches"]}
    assert {"participants", "date"} <= fields


def test_comparator_reports_missing_extra_and_duplicate_ids():
    from tournament_scheduler.pipeline.export_parity.comparator import compare_projections
    from tournament_scheduler.pipeline.export_parity.records import ArtifactProjection, TournamentRecord

    primary = ArtifactProjection(
        kind="xlsx",
        path="a.xlsx",
        exists=True,
        records=[
            TournamentRecord(tournament_id="rvv-1"),
            TournamentRecord(tournament_id="rvv-1"),
            TournamentRecord(tournament_id="rvv-2"),
        ],
    )
    secondary = ArtifactProjection(
        kind="html",
        path="a.html",
        exists=True,
        records=[TournamentRecord(tournament_id="rvv-1"), TournamentRecord(tournament_id="rvv-3")],
    )

    comparison = compare_projections(primary, secondary)

    assert comparison["duplicate_ids"]["xlsx"] == ["rvv-1"]
    assert comparison["extra_ids"] == ["rvv-3"]
    assert comparison["missing_ids"] == ["rvv-2"]


def test_edited_excel_game_row_is_detected(tmp_path):
    export_dir, xlsx, _ = _export_pair(tmp_path)
    workbook = openpyxl.load_workbook(xlsx)
    target_sheet = None
    for name in workbook.sheetnames:
        first = workbook[name].cell(row=1, column=1).value
        if isinstance(first, str) and first.startswith("Turnerings-ID: rvv-0001"):
            target_sheet = workbook[name]
            break
    assert target_sheet is not None
    header_row = next(
        row
        for row in range(1, target_sheet.max_row + 1)
        if tuple(target_sheet.cell(row=row, column=col).value for col in range(1, 5))
        == ("Runde", "Hjemmelag", "Bortelag", "Parallellbane")
    )
    target_sheet.cell(row=header_row + 1, column=2).value = "Feil Hjemmelag"
    workbook.save(xlsx)

    report = verify_export_parity(export_dir)

    assert report["status"] == STATUS_FAIL
    assert any(m["tournament_id"] == "rvv-0001" and m["field"] == "games" for m in report["comparison"]["mismatches"])


def test_three_cancelled_rows_compare_despite_different_presentation(tmp_path):
    teams = [Team(club=f"Club{i}", label=f"U10-{i}", age_group="U10") for i in range(4)]
    tournaments = [
        Tournament(
            id=f"rvv-000{i}",
            date=date(2026, 10, 10 + i),
            arena="Jar Isforum",
            age_group="U10",
            teams=teams,
            games=_games(teams),
            host_club="Jar",
            start_time="09:00",
            cancelled=True,
            cancellation_reason=f"Årsak {i}",
        )
        for i in range(3)
    ]
    plan = SeasonPlan(tournaments=tournaments, start_date=date(2026, 10, 1), end_date=date(2027, 4, 30))
    export_dir = tmp_path / "export"
    export_dir.mkdir()
    ice = {"U10": 150}
    SeasonPlanExporter().export(plan, str(export_dir / "season_plan.xlsx"), ice_time_for_age_group=ice)
    HtmlExporter().export(plan, str(export_dir / "season_plan.html"), ice_time_for_age_group=ice)

    report = verify_export_parity(export_dir)

    assert report["status"] == STATUS_PASS, report["reasons"]


def test_cancelled_tournament_moves_to_companion_page_but_stays_in_parity(tmp_path):
    export_dir, _, html = _export_pair(tmp_path)

    active_text = html.read_text(encoding="utf-8")
    assert '"id": "rvv-0004"' not in active_text
    companion = export_dir / CANCELLED_TOURNAMENTS_FILENAME
    assert companion.exists()
    assert '"id": "rvv-0004"' in companion.read_text(encoding="utf-8")

    report = verify_export_parity(export_dir)

    assert report["status"] == STATUS_PASS, report["reasons"]
    assert report["secondary"]["tournament_count"] == 4


def test_missing_cancelled_page_fails_parity_fail_closed(tmp_path):
    export_dir, _, _ = _export_pair(tmp_path)
    (export_dir / CANCELLED_TOURNAMENTS_FILENAME).unlink()

    report = verify_export_parity(export_dir)

    assert report["status"] == STATUS_FAIL
    assert "rvv-0004" in report["comparison"]["missing_ids"]


def test_edited_cancelled_reason_fails_parity(tmp_path):
    export_dir, _, _ = _export_pair(tmp_path)
    companion = export_dir / CANCELLED_TOURNAMENTS_FILENAME
    text = companion.read_text(encoding="utf-8")
    text = text.replace('"cr": "Regionalt sperret helg"', '"cr": "Feil \u00e5rsak"', 1)
    companion.write_text(text, encoding="utf-8")

    report = verify_export_parity(export_dir)

    assert report["status"] == STATUS_FAIL
    assert any(
        m["tournament_id"] == "rvv-0004" and m["field"] == "cancellation_reason"
        for m in report["comparison"]["mismatches"]
    )


# ---------------------------------------------------------------------------
# Review regressions: fail-closed publication invariant
# ---------------------------------------------------------------------------

import re  # noqa: E402

from tournament_scheduler.canonical_state import compute_canonical_state_revision  # noqa: E402
from tournament_scheduler.infrastructure.canonical_season_store import (  # noqa: E402
    CanonicalSeasonSnapshot,
    CanonicalSeasonStore,
)
from tournament_scheduler.pipeline.export_projection_guard import tournament_projection  # noqa: E402
from tournament_scheduler.serialization.season_plan import season_plan_to_dict  # noqa: E402

_CANONICAL_SEASON = "2026-2027"
_ICE = {"U10": 150, "U12": 120}
_TOURNAMENTS_RE = re.compile(r"(?m)^\s*const\s+TOURNAMENTS\s*=\s*(\[.*\]);\s*$")


def _canonical_export(tmp_path: Path):
    """Write a canonical-season store + a real export pair + lifecycle manifest."""

    plan = _fixture()
    problem = {"ice_time_minutes": _ICE}
    plan_dict = season_plan_to_dict(plan)
    projection = tournament_projection(plan_dict, problem)
    schedule = {
        "schema_version": 1,
        "season": _CANONICAL_SEASON,
        "plan": plan_dict,
        "verification_context": {"problem": problem},
    }
    decisions = {"schema_version": 1, "season": _CANONICAL_SEASON, "decisions": {}}
    revision = compute_canonical_state_revision(schedule, decisions)
    decisions["canonical_state_revision"] = revision
    CanonicalSeasonStore(tmp_path / "season").write(
        CanonicalSeasonSnapshot(season=_CANONICAL_SEASON, schedule=schedule, decisions=decisions)
    )

    export_dir = tmp_path / "export"
    export_dir.mkdir()
    approval = _approval_status()
    booking = _booking_status()
    SeasonPlanExporter().export(
        plan,
        str(export_dir / "season_plan.xlsx"),
        ice_time_for_age_group=_ICE,
        decision_status={"approval": approval, "booking": booking},
        season_metadata={"season": _CANONICAL_SEASON, "canonical_revision": revision},
    )
    HtmlExporter().export(
        plan,
        str(export_dir / "season_plan.html"),
        pipeline_meta={
            "canonical_revision": revision,
            "approval_status": approval,
            "booking_status": booking,
        },
        ice_time_for_age_group=_ICE,
    )
    SpondExporter().export(
        plan,
        str(export_dir / "season_plan_spond.xlsx"),
        ice_time_for_age_group=_ICE,
        season_metadata={"season": _CANONICAL_SEASON, "canonical_revision": revision},
    )
    (export_dir / "export_manifest.json").write_text(
        json.dumps(
            {
                "schema_version": 1,
                "canonical_season": _CANONICAL_SEASON,
                "canonical_revision": revision,
                "schedule_projection": projection,
                "lifecycle_status": "draft",
            }
        ),
        encoding="utf-8",
    )
    return export_dir, export_dir / "season_plan.xlsx", export_dir / "season_plan.html", projection, revision


def _mutate_html_payload(html: Path, mutate) -> None:
    text = html.read_text(encoding="utf-8")
    match = _TOURNAMENTS_RE.search(text)
    assert match is not None
    payload = json.loads(match.group(1))
    mutate(payload)
    replacement = "const TOURNAMENTS = " + json.dumps(payload, ensure_ascii=False) + ";"
    html.write_text(text[: match.start()] + replacement + text[match.end():], encoding="utf-8")


def test_publish_gate_blocks_deleted_canonical_xlsx(tmp_path):
    export_dir, xlsx, _, _, _ = _canonical_export(tmp_path)
    assert publish_parity_gate(export_dir=export_dir, repo_dir=tmp_path) is None

    xlsx.unlink()

    blocked = publish_parity_gate(export_dir=export_dir, repo_dir=tmp_path)
    assert blocked is not None
    assert any("artifact_missing" in str(evidence) for evidence in blocked.evidence)


def test_publish_gate_blocks_deleted_canonical_html(tmp_path):
    export_dir, _, html, _, _ = _canonical_export(tmp_path)
    html.unlink()

    blocked = publish_parity_gate(export_dir=export_dir, repo_dir=tmp_path)
    assert blocked is not None
    assert any("artifact_missing" in str(evidence) for evidence in blocked.evidence)


def test_canonical_publication_requires_each_revision_and_fails_closed(tmp_path):
    export_dir, xlsx, html, _, _ = _canonical_export(tmp_path)

    # Each artifact and the manifest must carry the required revision; blank
    # metadata is not a silent pass.
    blank = export_dir / "blank"
    blank.mkdir()
    workbook = openpyxl.load_workbook(xlsx)
    for row in workbook["Eksportmetadata"].iter_rows():
        if row[0].value == "Kanonisk revisjon":
            row[1].value = ""
    blank_xlsx = blank / "season_plan.xlsx"
    workbook.save(blank_xlsx)
    revision_meta = re.search(r'<meta\s+name="season-revision"\s+content="([^"]*)"', html.read_text(encoding="utf-8"))
    assert revision_meta is not None
    blank_html = html.read_text(encoding="utf-8").replace(revision_meta.group(1), "")
    (blank / "season_plan.html").write_text(blank_html, encoding="utf-8")
    # The cancelled-tournament page is part of the same HTML projection; copy
    # it too so this revision test isolates missing revision metadata rather
    # than tripping over an incomplete artifact set.
    companion = html.with_name(CANCELLED_TOURNAMENTS_FILENAME)
    if companion.exists():
        companion_text = companion.read_text(encoding="utf-8").replace(revision_meta.group(1), "")
        (blank / companion.name).write_text(companion_text, encoding="utf-8")

    report = verify_export_parity(
        blank,
        manifest={"canonical_revision": ""},
        canonical_publication=True,
        required_canonical_revision="rev-target",
    )
    assert report["status"] == STATUS_NOT_CHECKABLE
    assert any(reason["code"] == "missing_canonical_revision" for reason in report["reasons"])

    # An unreadable/absent canonical lookup is NOT_CHECKABLE, not a pass.
    report = verify_export_parity(
        export_dir,
        canonical_publication=True,
        canonical_lookup_failed=True,
    )
    assert report["status"] == STATUS_NOT_CHECKABLE
    assert any(reason["code"] == "canonical_state_unreadable" for reason in report["reasons"])


def test_projection_comparison_detects_end_and_roster_changes_in_both_artifacts(tmp_path):
    export_dir, xlsx, html, projection, revision = _canonical_export(tmp_path)

    workbook = openpyxl.load_workbook(xlsx)
    sheet = workbook["Sesongoversikt"]
    header = [cell.value for cell in sheet[1]]
    end_col = header.index("Sluttid") + 1
    teams_col = header.index("Lag") + 1
    id_col = header.index("Turnerings-ID") + 1
    row = next(
        index for index in range(2, sheet.max_row + 1) if sheet.cell(row=index, column=id_col).value == "rvv-0001"
    )
    sheet.cell(row=row, column=end_col).value = "23:59"
    sheet.cell(row=row, column=teams_col).value = "Feil Lag A, Feil Lag B"
    workbook.save(xlsx)

    def _mutate(payload):
        for entry in payload:
            if entry["id"] == "rvv-0001":
                entry["te"] = "23:59"
                for team in entry["p"]:
                    team["l"] = "Feil Lag A" if team["l"].endswith("0") else "Feil Lag B"

    _mutate_html_payload(html, _mutate)

    report = verify_export_parity(export_dir, expected_projection=projection)

    assert report["status"] == STATUS_FAIL, report["reasons"]
    fields = {m["field"] for m in report["projection_mismatches"]}
    assert {"end_time", "participants"} <= fields


def test_projection_comparison_detects_participant_identity_shift(tmp_path):
    export_dir, _, html, projection, _ = _canonical_export(tmp_path)

    def _mutate(payload):
        for entry in payload:
            if entry["id"] == "rvv-0001":
                entry["p"][0]["c"] = "FeilKlubb"

    _mutate_html_payload(html, _mutate)

    report = verify_export_parity(export_dir, expected_projection=projection)

    assert report["status"] == STATUS_FAIL, report["reasons"]
    assert any(m["field"] == "participants_identity" for m in report["projection_mismatches"])


def test_published_bundle_is_reverified_after_sanitization(tmp_path):
    from tournament_scheduler.pipeline import pages_bundle

    export_dir, _, _, _, _ = _canonical_export(tmp_path)
    bundle_dir = tmp_path / "public_bundle"
    result = pages_bundle.build_public_bundle(str(export_dir), str(bundle_dir))
    assert result.is_terminal_success
    # The cancellation page is part of the public projection and must travel
    # with the bundle; otherwise the published navbar link would be dead.
    assert (bundle_dir / CANCELLED_TOURNAMENTS_FILENAME).exists()

    manifest = json.loads((export_dir / "export_manifest.json").read_text(encoding="utf-8"))
    assert publish_parity_gate(export_dir=bundle_dir, repo_dir=tmp_path, manifest=manifest) is None

    # A sanitization/transformation that changes the published payload must be
    # caught by re-verifying the bundle, not only the source bytes.
    def _mutate(payload):
        payload[0]["a"] = "Feil arena"

    _mutate_html_payload(bundle_dir / "season_plan.html", _mutate)

    blocked = publish_parity_gate(export_dir=bundle_dir, repo_dir=tmp_path, manifest=manifest)
    assert blocked is not None


# ---------------------------------------------------------------------------
# Spond byte-readback regressions
# ---------------------------------------------------------------------------


def _spond_sheet(export_dir: Path):
    path = export_dir / "season_plan_spond.xlsx"
    workbook = openpyxl.load_workbook(path)
    sheet = workbook["Spond import"]
    columns = {cell.value: cell.column for cell in sheet[1]}
    return path, workbook, sheet, columns


def _spond_rows(sheet, columns, tournament_id: str) -> list[int]:
    return [
        row
        for row in range(2, sheet.max_row + 1)
        if sheet.cell(row=row, column=columns["RVV-ID"]).value == tournament_id
    ]


import pytest  # noqa: E402


@pytest.mark.parametrize(
    ("column", "replacement", "field"),
    [
        ("Startdato*", "11.10.2026", "date"),
        ("Starttidspunkt", "12:34", "start_time"),
        ("Sted", "Feil arena", "arena"),
        ("Vertsklubb", "Feil vert", "host_club"),
    ],
)
def test_spond_changed_placement_field_fails_with_exact_diagnostic(
    tmp_path, column, replacement, field
):
    export_dir, _, _ = _export_pair(tmp_path)
    path, workbook, sheet, columns = _spond_sheet(export_dir)
    for row in _spond_rows(sheet, columns, "rvv-0001"):
        sheet.cell(row=row, column=columns[column]).value = replacement
    workbook.save(path)

    report = verify_export_parity(export_dir, require_spond=True)

    assert report["status"] == STATUS_FAIL
    assert any(
        item["tournament_id"] == "rvv-0001" and item["field"] == field
        for item in report["spond_comparison"]["mismatches"]
    )


@pytest.mark.parametrize("mutation", ["remove", "add", "duplicate"])
def test_spond_participant_row_divergence_fails(tmp_path, mutation):
    export_dir, _, _ = _export_pair(tmp_path)
    path, workbook, sheet, columns = _spond_sheet(export_dir)
    rows = _spond_rows(sheet, columns, "rvv-0001")
    if mutation == "remove":
        sheet.delete_rows(rows[0], 1)
    else:
        values = [sheet.cell(row=rows[0], column=column).value for column in range(1, sheet.max_column + 1)]
        if mutation == "add":
            values[columns["Lag"] - 1] = "Ekstra U10"
            values[columns["Klubb"] - 1] = "Ekstra"
        sheet.append(values)
    workbook.save(path)

    report = verify_export_parity(export_dir, require_spond=True)

    assert report["status"] == STATUS_FAIL
    if mutation == "duplicate":
        assert any(reason["code"] == "duplicate_spond_row" for reason in report["reasons"])
    else:
        assert any(
            item["tournament_id"] == "rvv-0001"
            and item["field"] in {"participants", "participant_keys"}
            for item in report["spond_comparison"]["mismatches"]
        )


@pytest.mark.parametrize("mutation", ["missing", "extra"])
def test_spond_missing_or_extra_tournament_fails(tmp_path, mutation):
    export_dir, _, _ = _export_pair(tmp_path)
    path, workbook, sheet, columns = _spond_sheet(export_dir)
    rows = _spond_rows(sheet, columns, "rvv-0002")
    if mutation == "missing":
        for row in reversed(rows):
            sheet.delete_rows(row, 1)
    else:
        values = [sheet.cell(row=rows[0], column=column).value for column in range(1, sheet.max_column + 1)]
        values[columns["RVV-ID"] - 1] = "rvv-extra"
        sheet.append(values)
    workbook.save(path)

    report = verify_export_parity(export_dir, require_spond=True)

    assert report["status"] == STATUS_FAIL
    key = "missing_ids" if mutation == "missing" else "extra_ids"
    assert report["spond_comparison"][key]


def test_stale_spond_revision_cannot_pass_fresh_html(tmp_path):
    export_dir, _, _ = _export_pair(tmp_path)
    path, workbook, _, _ = _spond_sheet(export_dir)
    metadata = workbook["Eksportmetadata"]
    metadata.cell(row=2, column=2).value = OTHER_REVISION
    workbook.save(path)

    report = verify_export_parity(export_dir, require_spond=True)

    assert report["status"] == STATUS_FAIL
    assert any(reason["code"] == "stale_spond_revision" for reason in report["reasons"])


def test_cancelled_tournament_is_explicitly_excluded_from_spond(tmp_path):
    export_dir, _, _ = _export_pair(tmp_path)
    clean = verify_export_parity(export_dir, require_spond=True)
    assert clean["status"] == STATUS_PASS
    assert clean["spond_comparison"]["cancelled_ids_excluded"] == ["rvv-0004"]

    path, workbook, sheet, columns = _spond_sheet(export_dir)
    source = _spond_rows(sheet, columns, "rvv-0001")[0]
    values = [sheet.cell(row=source, column=column).value for column in range(1, sheet.max_column + 1)]
    values[columns["RVV-ID"] - 1] = "rvv-0004"
    sheet.append(values)
    workbook.save(path)

    report = verify_export_parity(export_dir, require_spond=True)
    assert report["status"] == STATUS_FAIL
    assert report["spond_comparison"]["cancelled_ids_in_spond"] == ["rvv-0004"]


@pytest.mark.parametrize("damage", ["missing", "unparseable"])
def test_required_spond_artifact_fails_closed(tmp_path, damage):
    export_dir, _, _ = _export_pair(tmp_path)
    path = export_dir / "season_plan_spond.xlsx"
    if damage == "missing":
        path.unlink()
    else:
        path.write_bytes(b"not an xlsx")

    report = verify_export_parity(export_dir, require_spond=True)

    assert report["status"] == STATUS_NOT_CHECKABLE
    assert any(reason["code"] in {"artifact_missing", "artifact_unreadable"} for reason in report["reasons"])


def _git(repo: Path, *args: str) -> str:
    import subprocess

    result = subprocess.run(
        ["git", *args], cwd=repo, check=True, capture_output=True, text=True
    )
    return result.stdout.strip()


def _published_fixture(tmp_path: Path) -> tuple[Path, Path]:
    import shutil

    generated = tmp_path / "generated"
    generated.mkdir()
    export_dir, _, _ = _export_pair(generated)
    repo = tmp_path / "published-repo"
    repo.mkdir()
    _git(repo, "init", "-b", "main")
    _git(repo, "config", "user.name", "Parity Test")
    _git(repo, "config", "user.email", "parity@example.invalid")
    (repo / "README").write_text("main", encoding="utf-8")
    _git(repo, "add", "README")
    _git(repo, "commit", "-m", "main")
    _git(repo, "checkout", "--orphan", "gh-pages")
    for child in list(repo.iterdir()):
        if child.name != ".git":
            child.unlink() if child.is_file() else shutil.rmtree(child)
    latest = repo / "latest"
    latest.mkdir()
    for name in (
        "season_plan.html",
        "season_plan.xlsx",
        "season_plan_spond.xlsx",
        CANCELLED_TOURNAMENTS_FILENAME,
    ):
        shutil.copy2(export_dir / name, latest / name)
    _git(repo, "add", "latest")
    _git(repo, "commit", "-m", "publish")
    return repo, latest


def test_published_verifier_reads_current_gh_pages_bytes_and_separates_freshness(tmp_path):
    from tournament_scheduler.pipeline.export_parity.published import (
        verify_published_export_parity,
    )

    repo, latest = _published_fixture(tmp_path)
    clean = verify_published_export_parity(
        repo_dir=repo,
        branch="gh-pages",
        remote="missing-remote",
        canonical_revision=REVISION,
    )
    assert clean["artifact_parity"]["status"] == STATUS_PASS
    assert clean["freshness"]["status"] == "FRESH"
    assert clean["published_commit"] == _git(repo, "rev-parse", "gh-pages")

    workbook_path = latest / "season_plan_spond.xlsx"
    workbook = openpyxl.load_workbook(workbook_path)
    sheet = workbook["Spond import"]
    columns = {cell.value: cell.column for cell in sheet[1]}
    row = _spond_rows(sheet, columns, "rvv-0001")[0]
    sheet.cell(row=row, column=columns["Sted"]).value = "Publisert feil arena"
    workbook.save(workbook_path)
    _git(repo, "add", "latest/season_plan_spond.xlsx")
    _git(repo, "commit", "-m", "diverge published workbook")

    divergent = verify_published_export_parity(
        repo_dir=repo,
        branch="gh-pages",
        remote="missing-remote",
        canonical_revision=REVISION,
    )
    assert divergent["artifact_parity"]["status"] == STATUS_FAIL
    # Provenance can still claim the current revision while actual artifact
    # bytes diverge; the two result dimensions must stay independent.
    assert divergent["freshness"]["status"] == "FRESH"
    assert any(
        mismatch["field"] == "arena"
        for mismatch in divergent["artifact_parity"]["spond_comparison"]["mismatches"]
    )
