"""Regression tests for the locked Python dependency workflow (GitHub issue #35)."""

from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def _read(relative: str) -> str:
    return (ROOT / relative).read_text(encoding="utf-8")


def test_committed_lock_has_exact_versions_hashes_and_expected_groups():
    lock = _read("requirements.lock")

    assert lock.startswith("# This file is generated by scripts/refresh-python-lock.sh")
    assert "pip-compile --all-extras" in lock
    assert "--generate-hashes" in lock
    assert "--hash=sha256:" in lock
    assert "requests==" in lock
    assert "pytest==" in lock
    assert "keyring==" not in lock
    assert "pyinstaller==" not in lock
    assert not re.search(r"^[a-zA-Z0-9_.-]+>=", lock, re.MULTILINE)


def test_refresh_script_keeps_pyproject_canonical_and_all_extras_locked():
    script = _read("scripts/refresh-python-lock.sh")
    requirements = _read("requirements.txt")

    assert "pyproject.toml" in script
    assert "--all-extras" in script
    assert "--allow-unsafe" in script
    assert "--generate-hashes" in script
    assert "requirements.lock" in script
    assert "pip-tools==7.6.0" in script
    assert "requirements.lock" in requirements
    assert "Deterministic installs must use requirements.lock" in requirements


def test_operator_install_uses_lock_without_resolving_deps():
    install = _read("scripts/install.sh")
    assert "requirements.lock" in install
    assert "--require-hashes" in install
    assert "--no-deps" in install
    assert "pip install -r requirements.txt" not in install


def test_ci_installs_locked_dependencies_and_has_lock_freshness_job():
    ci = _read(".github/workflows/ci.yml")

    assert "Python dependency lock freshness" in ci
    assert "scripts/check dependency-lock" in ci
    assert "requirements.lock" in ci
    assert "cache-dependency-path:" in ci
    assert "pip install --require-hashes -r requirements.lock" in ci
    assert "pip install --no-deps -e ." in ci
    assert "pip install -r requirements.txt" not in ci
    assert "pip install -e '.[test]'" not in ci
