#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
cd "$ROOT_DIR"

PYTHON_CMD=${PYTHON:-python3}
PIP_COMPILE_BIN=${PIP_COMPILE_BIN:-pip-compile}

if ! command -v "$PIP_COMPILE_BIN" >/dev/null 2>&1; then
  cat >&2 <<'EOF'
ERROR: pip-compile was not found.
Install pip-tools in an isolated environment, then rerun this command, for example:
  python3 -m venv /tmp/rvv-pip-tools
  /tmp/rvv-pip-tools/bin/python -m pip install --upgrade 'pip<26' 'pip-tools==7.6.0'
  PIP_COMPILE_BIN=/tmp/rvv-pip-tools/bin/pip-compile scripts/refresh-python-lock.sh
EOF
  exit 2
fi

# Compile to a fresh path rather than directly to requirements.lock. pip-compile
# otherwise treats an existing output file as an input constraint/reuse source,
# which can preserve stale pins or even a malformed hash from a damaged lock.
TMP_LOCK_DIR=$(mktemp -d "${TMPDIR:-/tmp}/rvv-python-lock.XXXXXX")
trap 'rm -rf "$TMP_LOCK_DIR"' EXIT
TMP_LOCK="$TMP_LOCK_DIR/requirements.lock"

"$PIP_COMPILE_BIN" \
  --resolver=backtracking \
  --strip-extras \
  --generate-hashes \
  --allow-unsafe \
  --all-extras \
  --output-file "$TMP_LOCK" \
  pyproject.toml

LOCK_PATH="$TMP_LOCK" "$PYTHON_CMD" - <<'PY'
import os
import re
from pathlib import Path

path = Path(os.environ["LOCK_PATH"])
text = path.read_text()

# Normalize environment/temp-path details in pip-compile's comment header so
# the committed lock is byte-for-byte stable across developer and CI hosts.
lines = text.splitlines()
for index, line in enumerate(lines[:12]):
    if line.startswith("#    pip-compile "):
        line = line.replace(" --no-index", "")
        line = re.sub(r"--output-file=\S+", "--output-file=requirements.lock", line)
        lines[index] = line
text = "\n".join(lines) + ("\n" if text.endswith("\n") else "")

header = "# This file is generated by scripts/refresh-python-lock.sh. Do not edit by hand.\n"
if not text.startswith(header):
    text = header + text
path.write_text(text)
PY

mv "$TMP_LOCK" requirements.lock

echo "Updated requirements.lock from pyproject.toml with all optional dependency groups"
