#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
cd "$ROOT_DIR"

PYTHON_CMD=${PYTHON:-python3}
PIP_COMPILE_BIN=${PIP_COMPILE_BIN:-pip-compile}

if ! command -v "$PIP_COMPILE_BIN" >/dev/null 2>&1; then
  cat >&2 <<'EOF'
ERROR: pip-compile was not found.
Install pip-tools in an isolated environment, then rerun this command, for example:
  python3 -m venv /tmp/rvv-pip-tools
  /tmp/rvv-pip-tools/bin/python -m pip install --upgrade 'pip<26' 'pip-tools==7.6.0'
  PIP_COMPILE_BIN=/tmp/rvv-pip-tools/bin/pip-compile scripts/refresh-python-lock.sh
EOF
  exit 2
fi

"$PIP_COMPILE_BIN" \
  --resolver=backtracking \
  --strip-extras \
  --generate-hashes \
  --allow-unsafe \
  --all-extras \
  --output-file requirements.lock \
  pyproject.toml

"$PYTHON_CMD" - <<'PY'
from pathlib import Path

path = Path("requirements.lock")
text = path.read_text()

# pip-compile may echo environment-derived --no-index into the generated
# command header (for example in a CI runner). That flag does not describe the
# repository's requested lock command and would make the committed lock vary
# by environment, so normalize it out of the comment only.
lines = text.splitlines()
for index, line in enumerate(lines[:12]):
    if line.startswith("#    pip-compile "):
        lines[index] = line.replace(" --no-index", "")
text = "\n".join(lines) + ("\n" if text.endswith("\n") else "")

header = "# This file is generated by scripts/refresh-python-lock.sh. Do not edit by hand.\n"
if not text.startswith(header):
    text = header + text
path.write_text(text)
PY

echo "Updated requirements.lock from pyproject.toml with all optional dependency groups"
